version: '3.3'
services:
  mylist:
    restart: always
    volumes:
      - './data:/opt/mylist/data'
    ports:
      - '5244:5244'
      - '5245:5245'
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=UTC
    container_name: mylist
    image: 'ghcr.io/surenkid/mylist:latest'
